### ISSUE TITLE
Нет текстур в двух объектах.

### ISSUE THREAD

**Issue by Creater3d** [TheSkyFather/MineralMod#3]
![6](https://user-images.githubusercontent.com/73776761/105797204-e8331500-5fa0-11eb-979f-5983e4c23709.png)
![7](https://user-images.githubusercontent.com/73776761/105797574-495ae880-5fa1-11eb-9e71-3f55b41ea209.png)

Электролизёр и водородный компрессор.

**Comment by TheSkyFather** [comment]
Мод закрыт и больше не поддерживается:(

**Comment by TheSkyFather** [comment]
Мод закрыт и больше не поддерживается :(
